 
version: '3.8'

services:
  lab01-app:
    image: lab01-img
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/course_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: vebprogramiranje
    depends_on:
      - postgres
    networks:
      - mynetwork

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: course_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vebprogramiranje
    ports:
      - "5433:5432"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
