apiVersion: v1
kind: Service
metadata:
  name: courseapp-service
  namespace: lab01-app
spec:
  selector:
    app: lab01-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP